/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

var self = require('sdk/self');
var tabs = require('sdk/tabs');
var ui = require('sdk/ui');

const PAGE_URL = 'resource://stopit-admin-at-stopit-dot-be/data/page.html';

var MainButton = ui.ActionButton({
	id: 'stopit-admin-btn',
	label: 'Stop-It Administration',
	icon: {
		16: './icon-16.png',
		32: './icon-32.png',
		64: './icon-64.png'
	},
	onClick: handleMainButtonClick
});

/**
 * Open main add-on's page.
 */
function handleMainButtonClick() {
	let pageUrl = self.data.url('page.html');
	// Check if page is already opened - if yes bring it to the foreground.
	for (let tab of tabs) {
		// We don't check exact match just the main URL
		if (tab.url == pageUrl) {
			tab.activate();
			return;
		}
	}
	// Homepage is not opened yet - open it
	tabs.open(pageUrl);
}

// ========================================================================
// Generated by JPM:

// a dummy function, to show how tests work.
// to see how to test this function, look at test/test-index.js
//function dummy(text, callback) {
//callback(text);
//}
//
//exports.dummy = dummy;
